#@ load("@ytt:data", "data")
---
#@ if data.values.custom.operators.crossplane_aws_provider.enabled:
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
 name: provider-aws
 annotations:
   kapp.k14s.io/change-group: compositions
   kapp.k14s.io/change-rule.0: "upsert after upserting pkgi"
   kapp.k14s.io/change-rule.1: "delete before deleting pkgi"
spec:
 package: #@ "xpkg.upbound.io/crossplane-contrib/provider-aws:{}".format(data.values.custom.operators.crossplane_aws_provider.provider_version)
---
apiVersion: v1
data:
  creds: #@ "{}".format(data.values.custom.operators.crossplane_aws_provider.crossplane_creds_secret)
kind: Secret
metadata:
  name: aws-provider-creds
  namespace: crossplane-system
---
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
 name: xpostgresqlinstances.bindable.database.example.org
spec:
 claimNames:
   kind: PostgreSQLInstance
   plural: postgresqlinstances
 connectionSecretKeys:
 - type
 - provider
 - host
 - port
 - database
 - username
 - password
 group: bindable.database.example.org
 names:
   kind: XPostgreSQLInstance
   plural: xpostgresqlinstances
 versions:
 - name: v1alpha1
   referenceable: true
   schema:
     openAPIV3Schema:
       properties:
         spec:
          properties:
            storageGB:
              type: integer
              default: 20
          type: object
       type: object
   served: true
---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
 labels:
   provider: "aws"
   vpc: "default"
 name: xpostgresqlinstances.bindable.aws.database.example.org
spec:
 compositeTypeRef:
   apiVersion: bindable.database.example.org/v1alpha1
   kind: XPostgreSQLInstance
 publishConnectionDetailsWithStoreConfigRef:
   name: default
 resources:
 - base:
     apiVersion: database.aws.crossplane.io/v1beta1
     kind: RDSInstance
     spec:
       forProvider:
         dbInstanceClass: db.t2.micro
         engine: postgres
         dbName: postgres
         engineVersion: "12"
         masterUsername: masteruser
         publiclyAccessible: true
         region: eu-west-1
         skipFinalSnapshotBeforeDeletion: true
       writeConnectionSecretToRef:
         namespace: crossplane-system
   connectionDetails:
   - name: type
     value: postgresql
   - name: provider
     value: aws
   - name: database
     value: postgres
   - fromConnectionSecretKey: username
   - fromConnectionSecretKey: password
   - name: host
     fromConnectionSecretKey: endpoint
   - fromConnectionSecretKey: port
   name: rdsinstance
   patches:
   - fromFieldPath: metadata.uid
     toFieldPath: spec.writeConnectionSecretToRef.name
     transforms:
     - string:
         fmt: '%s-postgresql'
         type: Format
       type: string
     type: FromCompositeFieldPath
   - fromFieldPath: spec.storageGB
     toFieldPath: spec.forProvider.allocatedStorage
     type: FromCompositeFieldPath
 - name: securityGroupRulePostgres
   base:
     apiVersion: ec2.aws.upbound.io/v1beta1
     kind: SecurityGroupRule
     spec:
       forProvider:
         region: eu-west-1
         type: ingress
         fromPort: 5432
         toPort: 5432
         protocol: tcp
         cidrBlocks:
           - 0.0.0.0/0  #! allow from anywhere inside the VPC (?)
         securityGroupIdSelector:
           matchControllerRef: true
         description: Everywhere
       deletionPolicy: Delete
---
apiVersion: services.apps.tanzu.vmware.com/v1alpha1
kind: ClusterInstanceClass
metadata:
  name: postgresql-rds
spec:
  description:
    short: Amazon RDS
  provisioner:
    crossplane:
      compositeResourceDefinition: xpostgresqlinstances.bindable.database.example.org

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: app-operator-postgresql-rds
  labels:
    apps.tanzu.vmware.com/aggregate-to-app-operator-cluster-access: "true"
rules:
- apiGroups:
  - "services.apps.tanzu.vmware.com"
  resources:
  - clusterinstanceclasses
  resourceNames:
  - postgresql-rds
  verbs:
  - claim
#@ end
