#@ load("@ytt:data", "data")
---
#@ if data.values.custom.tanzu_data_services.postgresql.enabled:
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: postgres-operator
  namespace: tap-install
  annotations:
    kapp.k14s.io/change-group: tds
    kapp.k14s.io/change-rule.0: "upsert after upserting pkgi"
    kapp.k14s.io/change-rule.1: "delete before deleting pkgi"
spec:
  serviceAccountName: tap-installer-sa
  packageRef:
    refName: postgres-operator.sql.tanzu.vmware.com
    versionSelection:
      constraints: #@ data.values.tanzu_data_services.postgresql.pkgi_version
#@ end
