#@ load("@ytt:data", "data")
---
#@ if data.values.custom.tanzu_data_services.postgresql.enabled or data.values.custom.tanzu_data_services.mysql.enabled:
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageRepository
metadata:
  name: tanzu-data-services-repository
  namespace: tap-install
  annotations:
    kapp.k14s.io/change-group: pkgr
spec:
  fetch:
    imgpkgBundle:
      image: #@ "{}:{}".format(data.values.custom.tanzu_data_services.pkgr_repo_url,data.values.custom.tanzu_data_services.pkgr_version)
#@ end
