secrets:
    sops:
        age_key: ENC[AES256_GCM,data:Y1yscgYImI2Q8ffK3MP3vgj6LnB1WrLxMhK+loZSm7AGqTXIxL/9seb8qfud2k3JWQEDVEBzR9pu4ss9Uutdot2/SR8YrpolHNPMWqOgT5d/LZMLqxHCfwuEHJ/guQ6KZXLXhf8cN5S567n/RdX3Of2M4KeBpy0hVRxG/PSvHP5+gppXWHAyrnam9IdV8fB/cRIaNaBkE0qxZ4EJ7OcCGR4mssHmoCTEo74Ofl6v6zKN3Rx/mU5ez3czcqih,iv:KoO2uQiV0EHvMBlSi1QikXUvBWLQVxylcfJzouHtFjk=,tag:oJJKGli4G5tFzd3iqHzCQw==,type:str]
        registry:
            hostname: ENC[AES256_GCM,data:+qFQ1WiS31dquhHDlm3oTU+tlJ8=,iv:uciNIlXvXgiTeBin+3O5/r7pXyvLFWzDzynApTr5JYg=,tag:ZYldJ/pE1jc1e/1Wqe4J2w==,type:str]
            username: ENC[AES256_GCM,data:hT+i9BA=,iv:FqL3cfJSANRo+hYwqfBfmgbfrzjnJNQv/3pN6rEYO3I=,tag:VjmJxdNhIlJ0s9omXRMN1g==,type:str]
            password: ENC[AES256_GCM,data:kILf5JqCf95F,iv:YWahzhcGsiRDxMMwZj8UG7daoiaY8rB/vkOYQBNhd+M=,tag:Q9F+8g1NRQ5qzRkG2W0C0A==,type:str]
        git:
            basic_auth:
                username: ENC[AES256_GCM,data:iXONokPx,iv:jLB+1zU6M6fJBk0H1eUyx7vby1a09fSi5ZqKURjwcKg=,tag:DW39Gx6krJR0roiy+OwZkg==,type:str]
                password: ENC[AES256_GCM,data:e3CMkv534XXbl5dWtM++hTul+QzLvYeaWDfaXnOf136GdIvio+NSaP4KbKqhUP1QuKtPoC5R3PX+hvUl1fo3BUZQb/vav4sknZf9zLiWeLI7LUkRxJk9AaCWfOGY,iv:xh4a+lZ/Xv5UEr0pmWz0J0p57LLHeeb8bYLQjx3mrHo=,tag:5wBuQTtiQiRBB+UZ6pR/Bg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14rwr23eu3s0c9tmtwrg3ftm6aqvz3n2hg4g046qgsa9gsjpw348qen7wes
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUdjFzWWM0Uzh3UFhudEp4
            ejgrOWxaRmF3Zmt3QXhqdm44K1RmaVhTQkVnClplYmtvQVFKT3pqQnRLd1BLRGJj
            K0wzZWh5OHA1QVIwL2JweXpseWJCaWsKLS0tIDEvdFI3REZVaVBYMkFieWovdlE1
            amVZdjQyTkY1YUsxVTBISVAvc25wQUEKco4WazobtAPzwbvLZkUpeBnBiaGPuSI/
            mdTB2htMZclE6/1P166TsGkP8l6yN6O3DieGeA/yKM+8wmsx7v0TLw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-07T13:36:40Z"
    mac: ENC[AES256_GCM,data:T9cKVf3kIGYT8I0le4TZr99YwfhyJLQiJUXxksd5SrrjxITViqgFqlkRma1elSdkhlDf69wEl6RYy0xHQ4JkDIJJmW/6Nffi49GNiE60FrIn+NQ+Cgfpn33VhbG50BN5ms7Ugd/YEPtDL0Zxu0bOmZAdh/ch2iMWRCsjNFDS5YI=,iv:yQ35C5/iwniuUykEI+2GHrXVlcZXawnNLRNtUeteASM=,tag:vw54htKBGllCTJYhdvLjgg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
