#@ load("@ytt:data", "data")
apiVersion: v1
kind: Secret
metadata:
  name: full-tbs-deps-tap-install-values
  namespace: tap-install
  annotations:
    kapp.k14s.io/change-group: tbs
type: Opaque
stringData:
  values.yaml: #@ "{}".format(data.values.custom.tbs_full_dependencies.pkgi_kp_default_repo)