secrets:
    sops: null
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14rwr23eu3s0c9tmtwrg3ftm6aqvz3n2hg4g046qgsa9gsjpw348qen7wes
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUdjFzWWM0Uzh3UFhudEp4
            ejgrOWxaRmF3Zmt3QXhqdm44K1RmaVhTQkVnClplYmtvQVFKT3pqQnRLd1BLRGJj
            K0wzZWh5OHA1QVIwL2JweXpseWJCaWsKLS0tIDEvdFI3REZVaVBYMkFieWovdlE1
            amVZdjQyTkY1YUsxVTBISVAvc25wQUEKco4WazobtAPzwbvLZkUpeBnBiaGPuSI/
            mdTB2htMZclE6/1P166TsGkP8l6yN6O3DieGeA/yKM+8wmsx7v0TLw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-07T13:17:55Z"
    mac: ENC[AES256_GCM,data:Dj7rVlrrP0HfLkCxj6p5IKwmD/3ga/tB+0d+kNzn0KxlXMg8GBR1T7xalx9TsS3qPGhgkfmcrRYdAyvNzgJ5rTJ/McSGwGVZRT8M2nAS8GOx+Dxxht9CuyalbRwwZIrYDZqt3QRk2Tz4on1/sYR9BhQ++cSmS9bRtvy/yO6HloI=,iv:YglSU+36ZF4WscYK4Qv9GN0ZvQnOjj9l2p2kSUzwu6w=,tag:y7AnOivkRcM9ruymKXxUuA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
