#@data/values-schema
#@overlay/match-child-defaults missing_ok=True
---
custom:
  acme:
    email: ""
  aws:
    region: eu-west-1
    route_fifty_three_zone_id: ""
    credentials:
      accessKey: ""
      secretKey: ""
  operators:
    crossplane_sql_provider:
      enabled: true
      provider_version: "v0.6.0"
      provider_package: "crossplane/provider-sql"
    spring_cloud_gateway:
      enabled: true
      package_version: "2.0.3"
      package_name: spring-cloud-gateway.tanzu.vmware.com
    tanzu_data_services:
      pkgr_version: "1.9.0"
      pkgr_repo_url: "registry.tanzu.vmware.com/packages-for-vmware-tanzu-data-services/tds-packages"
      postgresql:
        enabled: true
        pkgi_version: "2.0.1"
      mysql:
        enabled: true
        pkgi_version: "1.7.0"
    rabbitmq_oss:
      enabled: true
  compositions:
    mysql:
      enabled: true
    postgresql:
      enabled: true
    rabbitmq:
      enabled: true
    mssql:
      enabled: true
    mongodb:
      enabled: true
  tbs_full_dependencies:
    enabled: true
    pkgr_version: "1.10.10"
    pkgr_repo_url: registry.tanzu.vmware.com/tanzu-application-platform/full-tbs-deps-package-repo
  
