#@data/values-schema
#@overlay/match-child-defaults missing_ok=True
---
custom:
  gitops:
    write_permissions_user: ""
    github_token: ""
  acme:
    email: ""
  aws:
    region: eu-west-1
    route_fifty_three_zone_id: ""
    credentials:
      accessKey: ""
      secretKey: ""
  gcp:
    credentials:
      project_id: ""
      service_account_json_in_base64: ""
  operators:
    crossplane_sql_provider:
      enabled: true
      provider_version: "v0.6.0"
      provider_package: "crossplane/provider-sql"
    crossplane_aws_provider:
      enabled: true
      provider_version: "v0.33.0"
      provider_package: "crossplane/provider-aws"
      crossplane_creds_secret: ""
    spring_cloud_gateway:
      enabled: true
      package_version: "2.0.3"
      package_name: spring-cloud-gateway.tanzu.vmware.com
    tanzu_data_services:
      pkgr_version: "1.9.0"
      pkgr_repo_url: "registry.tanzu.vmware.com/packages-for-vmware-tanzu-data-services/tds-packages"
      postgresql:
        enabled: true
        pkgi_version: "2.0.1"
      mysql:
        enabled: true
        pkgi_version: "1.7.0"
    rabbitmq_oss:
      enabled: true
  compositions:
    mysql:
      enabled: true
    postgresql:
      enabled: true
    rabbitmq:
      enabled: true
    mssql:
      enabled: true
    mongodb:
      enabled: true
  tbs_full_dependencies:
    enabled: true
    pkgr_version: "1.6.1"
    pkgi_version: "0.2.3"
    pkgr_repo_url: harbor.tanzutime.com/tap/full-deps-package-repo
  
