#@ load("@ytt:data", "data")
---
#@ if data.values.custom.operators.crossplane-aws-provider.enabled:
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
 name: provider-aws
spec:
 package: #@ "xpkg.upbound.io/crossplane-contrib/provider-aws:{}".format(data.values.custom.operators.crossplane_aws_provider.provider_version
