#@ load("@ytt:data", "data")
---
#@ if data.values.custom.operators.crossplane_aws_provider.enabled:
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
 name: provider-aws
 annotations:
   kapp.k14s.io/change-group: compositions
   kapp.k14s.io/change-rule.0: "upsert after upserting pkgi"
   kapp.k14s.io/change-rule.1: "delete before deleting pkgi"
spec:
 package: #@ "xpkg.upbound.io/crossplane-contrib/provider-aws:{}".format(data.values.custom.operators.crossplane_aws_provider.provider_version)
---
apiVersion: v1
data:
  creds: #@ "{}".format(data.values.custom.operators.crossplane_aws_provider.crossplane_creds_secret)
kind: Secret
metadata:
  name: aws-provider-creds
  namespace: crossplane-system
---
apiVersion: aws.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
 name: default
spec:
 credentials:
   source: Secret
   secretRef:
     namespace: crossplane-system
     name: aws-provider-creds
     key: creds
#@ end
