---
tap_install:
  values:
    profile: iterate
    ceip_policy_disclosed: true
    buildservice:
      exclude_dependencies: true

    shared:
      ingress_domain: iteratetlv.tanzutime.com
      ingress_issuer: letsencrypt-contour-cluster-issuer

    api_auto_registration:
      tap_gui_url: https://tap-gui.viewtlv.tanzutime.com
      cluster_name: tap-iterate

    ootb_supply_chain_basic:
      registry:
        server: harbor.tanzutime.com
        repository: "apps"
      gitops:
        ssh_secret: ""
      git_implementation: libgit2

    contour:
      envoy:
        service:
          type: LoadBalancer

    grype:
      namespace: demos
      targetImagePullSecret: registry-credentials

    appliveview_connector:
      backend:
        sslDeactivated: "true"
        ingressEnabled: true
        host: appliveview.viewtlv.tanzutime.com
        port: "80"

    namespace_provisioner:
      controller: false
      gitops_install:
        ref: origin/main
        subPath: gitops-install
        url: https://github.com/odedia/tap-ns-provisioner.git
      additional_sources:
      - git:
          ref: origin/main
          subPath: databases
          url: https://github.com/odedia/tap-ns-provisioner.git
        path: _ytt_lib/databases
    excluded_packages:
      - crossplane.tanzu.vmware.com
      - namespace-provisioner.apps.tanzu.vmware.com
      - bitnami.services.tanzu.vmware.com
      - sso.apps.tanzu.vmware.com