---
tap_install:
  values:
    profile: iterate
    ceip_policy_disclosed: true
    buildservice:
      enable_automatic_dependency_updates: false
      exclude_dependencies: true

    shared:
      ingress_issuer: letsencrypt-contour-cluster-issuer

    supply_chain: basic

    api_auto_registration:
      tap_gui_url: https://tap-gui.viewtlv.tanzutime.com
      cluster_name: tap-iterate

    appsso:
      domain_name: apps.iteratetlv.tanzutime.com
      domain_template: "{{.Name}}-{{.Namespace}}.{{.Domain}}"

    ootb_supply_chain_basic:
      registry:
        server: harbor.tanzutime.com
        repository: "apps"
      gitops:
        ssh_secret: ""
      git_implementation: libgit2

    contour:
      envoy:
        service:
          annotations:      
            external-dns.alpha.kubernetes.io/hostname: *.iteratetlv.tanzutime.com
          type: LoadBalancer

    cnrs:
      domain_name: apps.iteratetlv.tanzutime.com
      domain_template: "{{.Name}}-{{.Namespace}}.{{.Domain}}"
      default_tls_secret: contour/letsencrypt-contour-cluster-issuer

    grype:
      namespace: demos
      targetImagePullSecret: registry-credentials

    appliveview_connector:
      backend:
        sslDeactivated: "true"
        ingressEnabled: true
        host: appliveview.viewtlv.tanzutime.com
        port: "80"
