---
tap_install:
  values:
    profile: iterate
    ceip_policy_disclosed: true
    buildservice:
      exclude_dependencies: true
    shared:
      ingress_domain: iteratetlv.tanzutime.com
      ingress_issuer: letsencrypt-contour-cluster-issuer
      kp_default_repository: harbor.tanzutime.com/tap/buildservice
      
    api_auto_registration:
      tap_gui_url: https://tap-gui.viewtlv.tanzutime.com
      cluster_name: tap-iterate

    ootb_supply_chain_basic:
      registry:
        server: harbor.tanzutime.com
        repository: "apps"
      gitops:
        ssh_secret: git-https
      git_implementation: libgit2

    contour:
      envoy:
        service:
          type: LoadBalancer

    grype:
      namespace: demos
      targetImagePullSecret: registry-credentials

    appliveview_connector:
      backend:
        sslDeactivated: "true"
        ingressEnabled: true
        host: appliveview.viewtlv.tanzutime.com
        port: "80"

    local_source_proxy:
      repository: harbor.tanzutime.com/apps/src
      push_secret:
        name: lsp-push-credentials
        namespace: tap-install
        create_export: true
    namespace_provisioner:
      controller: false
      sync_period: 30s
      # configure a repo that defines which namespaces should exist
      # for simplicity, it's the same one we have been using
      gitops_install:
        ref: origin/master
        subPath: clusters/tap-iterate/cluster-config/namespace-provisioner/namespaces
        url: https://github.com/odedia/tap-install-gitops-gke.git
        secretRef:
          name: sync-git
          namespace: tanzu-sync
          create_export: true
      additional_sources:
        # additional sources points to the resources we want to fill those namespaces with
        - git:
            url: https://github.com/odedia/tap-install-gitops-gke.git
            ref: origin/master
            subPath: clusters/tap-iterate/cluster-config/namespace-provisioner/namespace-resources
            secretRef:
              name: git-https
              namespace: tap-install
      default_parameters:
        supply_chain_service_account:
          secrets:
            - git-https