---
tap_install:
  values:
    profile: run
    ceip_policy_disclosed: true

    shared:
      ingress_domain: qatlv.tanzutime.com
      ingress_issuer: letsencrypt-contour-cluster-issuer

    api_auto_registration:
      tap_gui_url: https://tap-gui.viewtlv.tanzutime.com
      cluster_name: tap-qa

    contour:
      envoy:
        service:
          type: LoadBalancer

    appliveview_connector:
      backend:
        sslDeactivated: "true"
        ingressEnabled: true
        host: appliveview.viewtlv.tanzutime.com
        port: "80"
