#@ load("@ytt:data", "data")
#@ load("@ytt:base64", "base64")
---
apiVersion: v1
data:
  secret-access-key: #@ base64.encode(data.values.custom.aws.credentials.secretKey)
kind: Secret
metadata:
  annotations:
    kapp.k14s.io/change-group: "letsencrypt"
    kapp.k14s.io/change-rule.0: "upsert after upserting pkgi"
  creationTimestamp: null
  name: prod-route53-credentials-secret
  namespace: cert-manager
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  annotations:
    kapp.k14s.io/change-group: "letsencrypt"
    kapp.k14s.io/change-rule.0: "upsert after upserting pkgi"
  name: letsencrypt-contour-cluster-issuer
  namespace: tanzu-system-ingress
spec:
  acme:
    email: #@ data.values.custom.acme.email
    privateKeySecretRef:
      name: acme-account-key
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
      - dns01:
          route53:
            region: #@ data.values.custom.aws.region
            hostedZoneID: #@ data.values.custom.aws.route_fifty_three_zone_id
            accessKeyID: #@ data.values.custom.aws.credentials.accessKey
            secretAccessKeySecretRef:
              name: prod-route53-credentials-secret
              key: secret-access-key

